@startuml
set separator none
title Loans

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("LendHubApplication.LendHubApplication_boundary", "LendHubApplication", $tags="") {
  Component(LendHubApplication.LendHubApplication.Origination, "Origination", $techn="Module", $descr="", $tags="", $link="")
  Component(LendHubApplication.LendHubApplication.Shared, "Shared", $techn="Module", $descr="", $tags="", $link="")
  Component(LendHubApplication.LendHubApplication.Scoring, "Scoring", $techn="Module", $descr="", $tags="", $link="")
  Component(LendHubApplication.LendHubApplication.Loans, "Loans", $techn="Module", $descr="", $tags="", $link="")
  Component(LendHubApplication.LendHubApplication.Products, "Products", $techn="Module", $descr="", $tags="", $link="")
}

Rel(LendHubApplication.LendHubApplication.Origination, LendHubApplication.LendHubApplication.Products, "uses", $techn="", $tags="", $link="")
Rel(LendHubApplication.LendHubApplication.Origination, LendHubApplication.LendHubApplication.Scoring, "uses", $techn="", $tags="", $link="")
Rel(LendHubApplication.LendHubApplication.Origination, LendHubApplication.LendHubApplication.Shared, "uses", $techn="", $tags="", $link="")
Rel(LendHubApplication.LendHubApplication.Loans, LendHubApplication.LendHubApplication.Origination, "listens to", $techn="", $tags="", $link="")
Rel(LendHubApplication.LendHubApplication.Loans, LendHubApplication.LendHubApplication.Scoring, "depends on", $techn="", $tags="", $link="")
Rel(LendHubApplication.LendHubApplication.Loans, LendHubApplication.LendHubApplication.Shared, "uses", $techn="", $tags="", $link="")
Rel(LendHubApplication.LendHubApplication.Loans, LendHubApplication.LendHubApplication.Products, "uses", $techn="", $tags="", $link="")
Rel(LendHubApplication.LendHubApplication.Products, LendHubApplication.LendHubApplication.Shared, "uses", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml